
"""
Robust plotting module for optimization-based model calibration experiments.

Features
--------
- Structured dataset loader from compiled CSVs
- Convergence plots (mean ± std) grouped by algorithm
- Parameter distribution boxplots
- Error boxplots (% relative error)
- Hyperparameter set ranking by final fitness
- Centralized style configuration for easy visual adjustments

Expected CSV structure (generated by compile.py):
-------------------------------------------------
Iteracao
Media_Fitness
Desvio_Fitness
Run1_Fitness
Run2_Fitness
...
Run1_param1
Run2_param1
...

Folder structure expected:
log_dir/
    GA/
        set1/
            Convergencia_*.csv
        set2/
        set3/
    PSO/
    BO/

Improvements added
------------------
- Convergence computed using BEST-SO-FAR (cumulative minimum) per run
- Statistics recomputed from individual runs (mean ± std)
- Log-scale convergence plots
- Parameter boxplots centered around expected value
- Optional filtering using parameter search space
- Cleaner visual style
- Ranking uses best-so-far fitness
"""

import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime


PLOT_STYLE = {
    "font.family": "Times New Roman",
    "font.size": 12,
    "figure.figsize": (8, 5),
    "axes.grid": True,
    "grid.linestyle": "--",
    "grid.alpha": 0.4,
}

ALGO_COLORS = {
    "GA": "#1f77b4",
    "PSO": "#2ca02c",
    "BO": "#d62728"
}

plt.rcParams.update(PLOT_STYLE)


def load_experiment_dataset(log_dir):

    dataset = {}

    csv_files = glob.glob(
        os.path.join(log_dir, "**", "Convergencia_*.csv"),
        recursive=True
    )

    for f in csv_files:

        parts = f.split(os.sep)

        try:
            set_name = parts[-2]
            algo = parts[-3]
        except:
            continue

        df = pd.read_csv(f, sep=';', decimal='.', engine="python")

        dataset.setdefault(algo, {})
        dataset[algo][set_name] = df

    return dataset


def _save_or_show(fig, path=False):

    if path:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        fig.savefig(path, dpi=300, bbox_inches="tight")
        plt.close(fig)
    else:
        plt.show()


def _compute_best_so_far_stats(df):

    run_cols = [c for c in df.columns if "Run" in c and "Fitness" in c]

    if len(run_cols) == 0:
        mean = df["Media_Fitness"].cummin().values
        std = df["Desvio_Fitness"].values
        return mean, std

    runs = df[run_cols].values
    runs_best = np.minimum.accumulate(runs, axis=0)

    mean = runs_best.mean(axis=1)
    std = runs_best.std(axis=1)

    return mean, std


def plot_convergence_algorithm(dataset, algo, salvar_em=False):

    if algo not in dataset:
        print(f"{algo} not found in dataset")
        return

    fig, ax = plt.subplots()

    ax.spines["top"].set_visible(True)
    ax.spines["right"].set_visible(True)

    for set_name, df in dataset[algo].items():

        x = df["Iteracao"].values
        mean, std = _compute_best_so_far_stats(df)

        ax.plot(x, mean, label=set_name)

        ax.fill_between(
            x,
            mean - std,
            mean + std,
            alpha=0.2
        )

    ax.set_yscale("log")

    ax.set_xlabel("Iteration")
    ax.set_ylabel("Fitness")
    ax.set_title(f"Convergence – {algo}")

    ax.legend()

    path = None if not salvar_em else os.path.join(salvar_em, f"convergence_{algo}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png")

    _save_or_show(fig, path)


def plot_all_convergences(dataset, salvar_em=False):

    for algo in dataset:
        plot_convergence_algorithm(dataset, algo, salvar_em)


def _extract_parameter_values(df, param):

    cols = [c for c in df.columns if c.endswith("_" + param)]
    values = df.iloc[-1][cols].dropna().values

    return values


def plot_parameter_boxplot(
    dataset,
    param,
    expected_value=None,
    search_space=None,
    algo=None,
    salvar_em=False
):

    labels = []
    values = []

    for a in dataset:

        if algo and a != algo:
            continue

        for set_name, df in dataset[a].items():

            vals = _extract_parameter_values(df, param)

            if search_space and param in search_space:

                lo, hi = search_space[param]

                vals = vals[(vals >= lo) & (vals <= hi)]

            if len(vals) == 0:
                continue

            labels.append(f"{a}-{set_name}")
            values.append(vals)

    if len(values) == 0:
        return

    fig, ax = plt.subplots()

    ax.spines["top"].set_visible(True)
    ax.spines["right"].set_visible(True)

    ax.boxplot(values, tick_labels=labels, showmeans=False, showfliers=False)

    if expected_value is not None:

        ax.axhline(expected_value, linestyle="--", color="red", label="Expected")

        all_vals = np.concatenate(values)

        max_dev = np.max(np.abs(all_vals - expected_value))

        margin = max_dev * 1.2 if max_dev > 0 else abs(expected_value) * 0.05

        ax.set_ylim(
            expected_value - margin,
            expected_value + margin
        )

        ax.legend()

    ax.set_title(f"Parameter distribution – {param}")
    ax.set_ylabel(param)

    plt.xticks(rotation=45)

    path = None if not salvar_em else os.path.join(salvar_em, f"boxplot_param_{param}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png")

    _save_or_show(fig, path)


def plot_parameter_error_boxplot(
    dataset,
    expected_params,
    algo=None,
    salvar_em=False
):

    for a in dataset:

        if algo and a != algo:
            continue

        for set_name, df in dataset[a].items():

            labels = []
            errors = []

            for param, expected in expected_params.items():

                vals = _extract_parameter_values(df, param)

                err = np.abs(vals - expected) / np.abs(expected) * 100

                labels.append(param)
                errors.append(err)

            fig, ax = plt.subplots()

            ax.spines["top"].set_visible(True)
            ax.spines["right"].set_visible(True)

            ax.boxplot(errors, tick_labels=labels, showmeans=False, showfliers=False)

            ax.set_yscale("log")

            ax.set_ylabel("Relative error (%)")
            ax.set_title(f"Parameter error – {a} {set_name}")

            plt.xticks(rotation=45)

            path = None if not salvar_em else os.path.join(salvar_em, f"error_{a}_{set_name}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png")

            _save_or_show(fig, path)


def plot_set_ranking(dataset, salvar_em=False):

    labels = []
    fitness = []

    for algo in dataset:

        for set_name, df in dataset[algo].items():

            final = df["Media_Fitness"].cummin().iloc[-1]

            labels.append(f"{algo}-{set_name}")
            fitness.append(final)

    fig, ax = plt.subplots()

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    idx = np.argsort(fitness)

    labels = np.array(labels)[idx]
    fitness = np.array(fitness)[idx]

    ax.bar(labels, fitness)

    ax.set_yscale("log")

    ax.set_ylabel("Final fitness")
    ax.set_title("Hyperparameter set ranking")

    plt.xticks(rotation=45)

    path = None if not salvar_em else os.path.join(salvar_em, f"ranking_sets_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png")

    _save_or_show(fig, path)


def plot_all_results(
    log_dir,
    expected_params=None,
    search_space=None,
    salvar_em=False
):

    dataset = load_experiment_dataset(log_dir)

    plot_all_convergences(dataset, salvar_em)

    if expected_params:

        for param in expected_params:
            plot_parameter_boxplot(
                dataset,
                param,
                expected_params[param],
                search_space=search_space,
                salvar_em=salvar_em
            )

        plot_parameter_error_boxplot(
            dataset,
            expected_params,
            salvar_em=salvar_em
        )

    plot_set_ranking(dataset, salvar_em)

    return dataset
