
"""
Robust plotting module for optimization-based model calibration experiments.

Features
--------
- Structured dataset loader from compiled CSVs
- Convergence plots (mean ± std) grouped by algorithm
- Parameter distribution boxplots
- Error boxplots (% relative error)
- Hyperparameter set ranking by final fitness
- Centralized style configuration for easy visual adjustments

Expected CSV structure (generated by compile.py):
-------------------------------------------------
Iteracao
Media_Fitness
Desvio_Fitness
Run1_Fitness
Run2_Fitness
...
Run1_param1
Run2_param1
...

Folder structure expected:
log_dir/
    GA/
        set1/
            Convergencia_*.csv
        set2/
        set3/
    PSO/
    BO/

Author: Auto-generated research plotting toolkit
"""

import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# VISUAL STYLE CONFIGURATION (EDIT HERE)
# ============================================================

PLOT_STYLE = {
    "font.family": "Times New Roman",
    "font.size": 12,
    "figure.figsize": (8, 5),
    "axes.grid": True,
    "grid.linestyle": "--",
    "grid.alpha": 0.4,
}

ALGO_COLORS = {
    "GA": "#1f77b4",
    "PSO": "#2ca02c",
    "BO": "#d62728"
}


plt.rcParams.update(PLOT_STYLE)


# ============================================================
# DATA LOADER
# ============================================================

def load_experiment_dataset(log_dir):

    dataset = {}

    csv_files = glob.glob(os.path.join(log_dir, "**", "Convergencia_*.csv"), recursive=True)

    for f in csv_files:

        parts = f.split(os.sep)

        try:
            set_name = parts[-2]
            algo = parts[-3]
        except:
            continue

        df = pd.read_csv(f, sep=';', decimal='.', engine="python")

        dataset.setdefault(algo, {})
        dataset[algo][set_name] = df

    return dataset


# ============================================================
# INTERNAL UTILITIES
# ============================================================

def _save_or_show(fig, path=None, save=True):

    if save and path:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        fig.savefig(path, dpi=300, bbox_inches="tight")
        plt.close(fig)
    else:
        plt.show()


# ============================================================
# CONVERGENCE PLOTS
# ============================================================

def plot_convergence_algorithm(dataset, algo, save=True, outdir="plots"):

    if algo not in dataset:
        print(f"{algo} not found in dataset")
        return

    fig, ax = plt.subplots()

    for set_name, df in dataset[algo].items():

        x = df["Iteracao"].values
        mean = df["Media_Fitness"].values
        std = df["Desvio_Fitness"].values

        ax.plot(x, mean, label=set_name)

        ax.fill_between(
            x,
            mean - std,
            mean + std,
            alpha=0.2
        )

    ax.set_yscale("log")
    ax.set_xlabel("Iteration")
    ax.set_ylabel("Fitness")
    ax.set_title(f"Convergence – {algo}")
    ax.legend()

    path = os.path.join(outdir, f"convergence_{algo}.png")

    _save_or_show(fig, path, save)


def plot_all_convergences(dataset, save=True, outdir="plots"):

    for algo in dataset:
        plot_convergence_algorithm(dataset, algo, save, outdir)


# ============================================================
# PARAMETER DISTRIBUTION BOXPLOTS
# ============================================================

def _extract_parameter_values(df, param):

    cols = [c for c in df.columns if c.endswith("_" + param)]
    values = df.iloc[-1][cols].dropna().values

    return values


def plot_parameter_boxplot(dataset, param, expected_value=None,
                           algo=None, save=True, outdir="plots"):

    labels = []
    values = []

    for a in dataset:

        if algo and a != algo:
            continue

        for set_name, df in dataset[a].items():

            vals = _extract_parameter_values(df, param)

            labels.append(f"{a}-{set_name}")
            values.append(vals)

    fig, ax = plt.subplots()

    ax.boxplot(values, tick_labels=labels, showmeans=True)

    if expected_value is not None:
        ax.axhline(expected_value, linestyle="--", color="red", label="Expected")

    ax.set_title(f"Parameter distribution – {param}")
    ax.set_ylabel(param)
    ax.legend()

    plt.xticks(rotation=45)

    path = os.path.join(outdir, f"boxplot_param_{param}.png")

    _save_or_show(fig, path, save)


# ============================================================
# PARAMETER ERROR BOXPLOTS (%)
# ============================================================

def plot_parameter_error_boxplot(dataset, expected_params,
                                 algo=None, save=True, outdir="plots"):

    for a in dataset:

        if algo and a != algo:
            continue

        for set_name, df in dataset[a].items():

            labels = []
            errors = []

            for param, expected in expected_params.items():

                vals = _extract_parameter_values(df, param)

                err = np.abs((vals - expected) / expected) * 100

                labels.append(param)
                errors.append(err)

            fig, ax = plt.subplots()

            ax.boxplot(errors, tick_labels=labels, showmeans=True)

            ax.set_yscale("log")

            ax.set_ylabel("Relative error (%)")
            ax.set_title(f"Parameter error – {a} {set_name}")

            plt.xticks(rotation=45)

            path = os.path.join(outdir, f"error_{a}_{set_name}.png")

            _save_or_show(fig, path, save)


# ============================================================
# HYPERPARAMETER SET RANKING
# ============================================================

def plot_set_ranking(dataset, save=True, outdir="plots"):

    labels = []
    fitness = []

    for algo in dataset:

        for set_name, df in dataset[algo].items():

            final = df["Media_Fitness"].iloc[-1]

            labels.append(f"{algo}-{set_name}")
            fitness.append(final)

    fig, ax = plt.subplots()

    idx = np.argsort(fitness)

    labels = np.array(labels)[idx]
    fitness = np.array(fitness)[idx]

    ax.bar(labels, fitness)

    ax.set_yscale("log")

    ax.set_ylabel("Final fitness")
    ax.set_title("Hyperparameter set ranking")

    plt.xticks(rotation=45)

    path = os.path.join(outdir, "ranking_sets.png")

    _save_or_show(fig, path, save)


# ============================================================
# MASTER FUNCTION
# ============================================================

def plot_all_results(log_dir, expected_params=None,
                     save=True, outdir="plots"):

    dataset = load_experiment_dataset(log_dir)

    plot_all_convergences(dataset, save, outdir)

    if expected_params:

        for param in expected_params:
            plot_parameter_boxplot(dataset, param,
                                   expected_params[param],
                                   save=save, outdir=outdir)

        plot_parameter_error_boxplot(dataset, expected_params,
                                     save=save, outdir=outdir)

    plot_set_ranking(dataset, save, outdir)

    return dataset
