
"""
Robust plotting module for optimization-based model calibration experiments.

Features
--------
- Structured dataset loader from compiled CSVs
- Convergence plots (mean ± std) grouped by algorithm
- Parameter distribution boxplots
- Error boxplots (% relative error)
- Hyperparameter set ranking by final fitness
- Centralized style configuration for easy visual adjustments

Expected CSV structure (generated by compile.py):
-------------------------------------------------
Iteracao
Media_Fitness
Desvio_Fitness
Run1_Fitness
Run2_Fitness
...
Run1_param1
Run2_param1
...

Folder structure expected:
log_dir/
    GA/
        set1/
            Convergencia_*.csv
        set2/
        set3/
    PSO/
    BO/

Improvements added
------------------
- Convergence computed using BEST-SO-FAR (cumulative minimum) per run
- Statistics recomputed from individual runs (mean ± std)
- Log-scale convergence plots
- Parameter boxplots centered around expected value
- Optional filtering using parameter search space
- Cleaner visual style
- Ranking uses best-so-far fitness
"""

import os
import glob
import numpy as np
import pandas as pd
from datetime import datetime
import math

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.ticker import FuncFormatter


PLOT_STYLE = {
    "font.family": "Times New Roman",
    "font.size": 14,
    "figure.figsize": (16, 6),
    "axes.grid": True,
    "grid.linestyle": "--",
    "grid.alpha": 0.4,
    "axes.linewidth": 0.8,
}

ALGO_COLORS = {
    "GA": "#1f77b4",
    "PSO": "#2ca02c",
    "BO": "#d62728"
}

ALGO_AXES = {
    "GA": ["Generations", "Gerações"],
    "PSO": ["Iterations", "Iterações"],
    "BO": ["Evaluations", "Avaliações"]
}



class Plotter:
    def __init__(self, log_dir, save_dir=None, portuguese=True):
        self.dataset = self.load_experiment_dataset(log_dir)
        self.salvar_em = None
        self.save_path(save_dir) # configura self.salvar_em
        self.portuguese = portuguese

        self.ALGO_AXES = ALGO_AXES
        self.update_plot_style(PLOT_STYLE)

        self.labelpad = 8
        self.titlepad = 20
        self.minorfigsize = (8, 5)

    def save_path(self, save_dir):
        self.salvar_em = None if not save_dir else os.path.join(save_dir, f"Plot_{datetime.now().strftime('%Y%m%d_%H%M%S')}")

    @staticmethod
    def update_plot_style(plot_style:dict):
        plt.rcParams.update(plot_style)

    @staticmethod
    def load_experiment_dataset(log_dir):

        dataset = {}

        csv_files = glob.glob(
            os.path.join(log_dir, "**", "Convergencia_*.csv"),
            recursive=True
        )

        for f in csv_files:

            parts = f.split(os.sep)

            try:
                algo = os.path.basename(os.path.dirname(os.path.dirname(f)))
                set_name = os.path.basename(os.path.dirname(f))
            except:
                continue

            df = pd.read_csv(f, sep=';', decimal='.', engine="python")

            dataset.setdefault(algo, {})
            dataset[algo][set_name] = df

        return dataset

    @staticmethod
    def _save_or_show(fig, path=False):

        if path:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            fig.savefig(path, dpi=300, bbox_inches="tight")
            plt.close(fig)
        else:
            plt.show()

    @staticmethod
    def _compute_best_so_far_stats(df):

        run_cols = [c for c in df.columns if c.startswith("Run") and c.endswith("Fitness")]

        if len(run_cols) == 0:
            mean = df["Media_Fitness"].cummin().values
            std = df["Desvio_Fitness"].values
            return mean, std

        runs = df[run_cols].values
        runs_best = np.minimum.accumulate(runs, axis=0)

        mean = runs_best.mean(axis=1)
        std = runs_best.std(axis=1)

        return mean, std

    @staticmethod
    def format_function(ymin, casas_decimais):
        # Cria uma função que decide como escrever cada número no eixo
        def formatar_marcadores(valor, posicao):

            # se ymin (fit) retorna com mais precisão
            if abs(valor - ymin) < 1e-8:
                return f"{valor:.2e}" if casas_decimais >= 3 else f"{valor:.{casas_decimais + 1}f}"

            # se 0 retorna 0
            if abs(valor) < 1e-8:
                return "0"

            if casas_decimais > 2:
                # O ".1e" formata como "5.0e-03". Se quiser mais precisão, mude para ".2e"
                return f"{valor:.1e}"

            # Condição Padrão: Passo normal (1 ou 2 casas) -> Usa decimal comum
            return f"{valor:.{casas_decimais}f}"

        return formatar_marcadores

    def plot_convergence_algorithm(self, algo, filter_sets:dict= {}, legenda=True, save:str|None=None):
        """
        Gráfico de convergência em escala logarítmica
        """

        if algo not in self.dataset:
            print(f"{algo} not found in dataset")
            return

        fig, ax = plt.subplots()

        ax.spines["top"].set_visible(True)
        ax.spines["right"].set_visible(True)

        ylim = 0
        ymin = 0

        for i, (set_name, df) in enumerate(self.dataset[algo].items(), start=1):

            if algo in filter_sets and i not in filter_sets[algo]:
                continue

            x = df["Iteracao"].values
            mean, std = self._compute_best_so_far_stats(df)

            ax.plot(x, mean, label=set_name)

            ax.fill_between(
                x,
                mean - std,
                mean + std,
                alpha=0.2
            )

            ylim = max(ylim, np.max(mean))

            ymin = min(ymin or np.min(mean), np.min(mean))

        ymax = ylim * 1.05
        ax.set_ylim(bottom=ymin,top=ymax)
        ax.set_yscale("log")

        # melhoria no eixo y

        # 1. Pede para o Matplotlib dividir o espaço em aproximadamente 6 "pedaços" bonitos
        ax.yaxis.set_major_locator(ticker.MaxNLocator(nbins=6))

        #####

        # 2. Pega a lista de marcadores automáticos gerados pelo MaxNLocator
        ticks_atuais = ax.get_yticks()

        # 3. Define uma tolerância visual (ex: 5% da diferença entre max e min)
        # para apagar ticks automáticos que estejam muito colados nos seus limites
        tolerancia = (ymax- ymin) * 0.05

        # 4. Mantém apenas os ticks que estão longe o suficiente do ymin e do ymax
        ticks_limpos = [t for t in ticks_atuais if abs(t - ymin) > tolerancia and abs(t - ymax) > tolerancia]

        # 5. Insere os seus marcadores exatos na lista e ordena
        ticks_limpos.append(ymin)  # Se quiser marcar o topo exato do gráfico, use ymax * 1.05
        ticks_limpos.sort()

        # 6. Aplica a nova lista definitiva no eixo
        ax.set_yticks(ticks_limpos)

        ax.set_ylim(bottom=ymin,top=ymax)

        # Formata para não usar notação científica (opcional, para ficar como 0.05, 0.10, etc.)
        # formatter = ticker.ScalarFormatter()
        # formatter.set_scientific(False)
        # ax.yaxis.set_major_formatter(formatter)

        passo = ticks_atuais[1] - ticks_atuais[0]
        if passo > 0:
            casas_decimais = max(0, -math.floor(math.log10(passo)))
        else:
            casas_decimais = 2  # Segurança caso dê zero

        formatar_marcadores = self.format_function(ymin, casas_decimais)

        # Aplica a sua função como o formatador oficial do eixo Y
        ax.yaxis.set_major_formatter(FuncFormatter(formatar_marcadores))

        #####

        ax.yaxis.set_minor_locator(ticker.NullLocator())

        #####

        ax.set_xlabel(self.ALGO_AXES[algo][self.portuguese], labelpad=self.labelpad)
        ax.set_ylabel("Fitness", labelpad=self.labelpad)
        ax.set_title(f"{'Convergence' if not self.portuguese else 'Convergência'}: {algo}", pad=self.titlepad)

        if legenda: ax.legend()

        if not save:
            path = None if not self.salvar_em else os.path.join(self.salvar_em, f"convergence_{algo}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png")
        else:
            path = os.path.join(save, f"convergence_{algo}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png")

        self._save_or_show(fig, path)


    def plot_all_convergences(self, filter_sets:dict= {}, legenda=True):

        for algo in self.dataset:
            self.plot_convergence_algorithm(algo, filter_sets, legenda)


    @staticmethod
    def _extract_parameter_values(df, param):

        cols = [c for c in df.columns if c.endswith("_" + param)]
        values = df.iloc[-1][cols].dropna().values

        return values


    def plot_parameter_boxplot(self,
        param,
        key_to_name: dict = None, # dicionário que relaciona key com o nome completo do parâmetro para legenda
        expected_value: dict=None,
        search_space: dict=None,
        algo:list[str]=None,
        filter_sets:dict={},
        save: str | None = None
    ):

        labels = []
        values = []

        for a in self.dataset:

            if algo and a not in algo:
                continue

            for i, (set_name, df) in enumerate(self.dataset[a].items(), start=1):

                if a in filter_sets and i not in filter_sets[a]:
                    continue

                vals = self._extract_parameter_values(df, param)

                if search_space and param in search_space:

                    lo, hi = search_space[param]

                    vals = vals[(vals >= lo) & (vals <= hi)]

                if len(vals) == 0:
                    continue

                if algo and len(algo) == 1:
                    labels.append(f"{set_name}") # não repete o nome do algoritmo várias vezes caso seja vários conjuntos dele
                elif filter_sets and len(filter_sets[a]) == 1:
                    labels.append(f"{a}")
                else:
                    labels.append(f"{a} ({set_name})")
                values.append(vals)

        if len(values) == 0:
            return

        fig, ax = plt.subplots(figsize=self.minorfigsize if len(values)<=3 else None)

        ax.spines["top"].set_visible(True)
        ax.spines["right"].set_visible(True)

        ax.boxplot(values, tick_labels=labels, showmeans=False, showfliers=False)

        if expected_value is not None:

            ax.axhline(expected_value, linestyle="--", color="blue", label="Expected")

            all_vals = np.concatenate(values)

            max_dev = np.max(np.abs(all_vals - expected_value))

            margin = max_dev * 1.2 if max_dev > 0 else abs(expected_value) * 0.05

            ax.set_ylim(
                expected_value - margin,
                expected_value + margin
            )

            # ax.legend() # não é necessária legenda

        paramname = param if not key_to_name else key_to_name[param]

        ax.set_title(f"{"Parameter distribution" if not self.portuguese else "Distribuição do Parâmetro"}: {param}", pad=20)
        ax.set_ylabel(paramname)

        plt.xticks(rotation=0 if len(values)<=3 else 45)

        if not save:
            path = None if not self.salvar_em else os.path.join(self.salvar_em, f"boxplot_param_{param}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png")
        else:
            path = os.path.join(save, f"boxplot_param_{param}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png")

        self._save_or_show(fig, path)


    def plot_parameter_error_boxplot(self,
        expected_params,
        algo=None,
        save: str | None = None
    ):

        for a in self.dataset:

            if algo and a not in algo:
                continue

            for set_name, df in self.dataset[a].items():

                labels = []
                errors = []

                for param, expected in expected_params.items():

                    vals = self._extract_parameter_values(df, param)

                    err = np.abs(vals - expected) / np.abs(expected) * 100

                    labels.append(param)
                    errors.append(err)

                fig, ax = plt.subplots()

                ax.spines["top"].set_visible(True)
                ax.spines["right"].set_visible(True)

                ax.boxplot(errors, tick_labels=labels, showmeans=False, showfliers=False)

                ax.set_yscale("log")

                ax.set_ylabel("Relative error (%)" if not self.portuguese else "Erro Relativo (%)")
                ax.set_title(f"{"Parameter error" if not self.portuguese else "Erro de parâmetros"}: {a} ({set_name})", pad=20)

                plt.xticks(rotation=45)

                if not save:
                    path = None if not self.salvar_em else os.path.join(self.salvar_em, f"error_{a}_{set_name}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png")
                else:
                    path = os.path.join(save, f"error_{a}_{set_name}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png")

                self._save_or_show(fig, path)

    def plot_convergence_vs_time_logs(
            self,
            algos: list,
            logs_dir: str | dict,
            legenda: bool = True,
            tmax: float | None = None,
            ymax: float | None = None,
            ymax_percentile: float | None = None,
            cut_ini_pop: bool = False
    ):
        """
        Convergência (best-so-far) × Tempo usando logs originais {algo}_*.csv.

        - Lê todos os logs do diretório com padrão {algo}_*.csv
        - Calcula mínimo cumulativo de fitness por avaliação
        - Interpola runs para obter média ± desvio
        - Limita o eixo de tempo ao menor tempo máximo entre algoritmos

        :param logs_dir: pode passar um diretório comum ou dicionário relacionando algoritmo
        """

        fig, ax = plt.subplots()

        ax.spines["top"].set_visible(True)
        ax.spines["right"].set_visible(True)

        algo_runs = {}
        algo_max_times = []
        all_means = []

        # -----------------------------
        # 1) carregar logs
        # -----------------------------

        for algo in algos:

            if isinstance(logs_dir, dict):
                pattern = os.path.join(logs_dir[algo], f"{algo}_*.csv")
            else:
                pattern = os.path.join(logs_dir, f"{algo}_*.csv")

            files = sorted(glob.glob(pattern))

            if not files:
                print(f"[AVISO] Nenhum log encontrado para {algo}")
                continue

            runs = []

            for f in files:

                try:
                    df = pd.read_csv(f, sep=None, engine="python")
                except:
                    continue

                if "Fitness" not in df.columns or "Time (s)" not in df.columns:
                    continue

                # --------------------------------------------------
                # remover população inicial
                # --------------------------------------------------

                time_offset = 0.0

                if cut_ini_pop:

                    if "Iteration" in df.columns:

                        iter_col = pd.to_numeric(df["Iteration"], errors="coerce")

                        # tempo do final da população inicial
                        init_mask = iter_col == 0

                        if init_mask.any():
                            time_offset = pd.to_numeric(
                                df.loc[init_mask, "Time (s)"], errors="coerce"
                            ).max()

                        df = df[iter_col > 0]

                    if df.empty:
                        continue

                fitness = pd.to_numeric(df["Fitness"], errors="coerce").values
                tempo = pd.to_numeric(df["Time (s)"], errors="coerce").values - time_offset

                mask = (~np.isnan(fitness)) & (~np.isnan(tempo))

                if mask.sum() < 2:
                    continue

                fitness = fitness[mask]
                tempo = tempo[mask]

                order = np.argsort(tempo)

                tempo = tempo[order]
                fitness = fitness[order]

                best = np.minimum.accumulate(fitness)

                runs.append((tempo, best))

            if not runs:
                continue

            algo_runs[algo] = runs
            algo_max_times.append(max(r[0][-1] for r in runs))

        if not algo_runs:
            print("Nenhum dado válido encontrado.")
            return

        # -----------------------------
        # 2) definir limite temporal
        # -----------------------------

        t_max_common = min(algo_max_times)

        if tmax is not None:
            t_max_common = min(t_max_common, tmax)

        ylim = 0
        ymin = None

        curves = []

        # -----------------------------
        # 3) processar cada algoritmo
        # -----------------------------

        for algo, runs in algo_runs.items():

            common_time = np.linspace(0, t_max_common, 400)

            interpolated = []

            for tempo, best in runs:

                mask = tempo <= t_max_common

                tempo = tempo[mask]
                best = best[mask]

                if len(tempo) < 2:
                    continue

                interp = np.interp(
                    common_time,
                    tempo,
                    best,
                    left=best[0],
                    right=best[-1]
                )

                interpolated.append(interp)

            if not interpolated:
                continue

            interpolated = np.array(interpolated)

            mean = interpolated.mean(axis=0)
            std = interpolated.std(axis=0)

            all_means.extend(mean)

            curves.append((algo, common_time, mean, std))

            ylim = max(ylim, np.max(mean))

            if ymin is None:
                ymin = np.min(mean)
            else:
                ymin = min(ymin, np.min(mean))

        # --------------------------------------------------
        # ajuste do ymax
        # --------------------------------------------------

        if ymax_percentile is not None and len(all_means) > 0:
            ymax_auto = np.percentile(all_means, ymax_percentile)
        else:
            ymax_auto = ylim * 1.05

        if ymax is None:
            ymax = ymax_auto

        # log não aceita zero
        ymin = max(ymin, 1e-12)

        # -----------------------------
        # 4) plotar curvas (com clipping)
        # -----------------------------

        for algo, common_time, mean, std in curves:
            mean = np.clip(mean, ymin, ymax)
            upper = np.clip(mean + std, ymin, ymax)
            lower = np.clip(mean - std, ymin, ymax)

            ax.plot(
                common_time,
                mean,
                label=algo,
                color=ALGO_COLORS.get(algo, None)
            )

            ax.fill_between(
                common_time,
                lower,
                upper,
                alpha=0.2,
                color=ALGO_COLORS.get(algo, None)
            )

        ax.set_ylim(bottom=ymin, top=ymax)

        ax.set_yscale("log")

        # --------------------------------------------------
        # 5) configuração eixo Y
        # --------------------------------------------------

        # --------------------------------------------------
        # eixo Y para escala log
        # --------------------------------------------------

        # --------------------------------------------------
        # eixo Y para escala log (ticks robustos)
        # --------------------------------------------------

        ax.set_yscale("log")

        # gerar ticks log distribuídos no intervalo real
        ticks = np.geomspace(ymin, ymax, 6)

        ax.set_yticks(ticks)

        ax.yaxis.set_major_formatter(
            FuncFormatter(lambda y, _: f"{y:.2g}")
        )

        ax.yaxis.set_minor_locator(ticker.NullLocator())

        # -----------------------------
        # 6) eixo X
        # -----------------------------

        ax.set_xlim(left=0, right=t_max_common)

        ax.set_xlabel("Tempo de processamento (s)", labelpad=self.labelpad)
        ax.set_ylabel("Fitness", labelpad=self.labelpad)

        ax.set_title("Convergência: Fitness × Tempo", pad=self.titlepad)

        if legenda:
            ax.legend()

        path = None if not self.salvar_em else os.path.join(
            self.salvar_em,
            f"convergence_time_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        )

        self._save_or_show(fig, path)


    def plot_all_results(self, param_keys, key_to_name=None, param_expected_values=None, param_search_space=None, filter_sets={}):

        salvamento_padrao = self.salvar_em

        # plots por algoritmo
        for algo in self.dataset:

            self.salvar_em = None if not self.salvar_em else os.path.join(salvamento_padrao, algo)

            print(f"\nPlotando gráficos para {algo} . . .\n")

            self.plot_convergence_algorithm(algo)

            for param in param_keys:
                self.plot_parameter_boxplot(param, algo=algo, key_to_name=key_to_name, expected_value=param_expected_values[param] if param_expected_values else None, search_space=param_search_space)

            if param_expected_values:
                self.plot_parameter_error_boxplot(param_expected_values, algo=algo)

        # plots conjuntos

        self.salvar_em = salvamento_padrao

        print(f"\nPlotando gráficos conjuntos: . . .")
        if filter_sets:
            print (f"{algo} ({filter_sets[algo]})" for algo in self.dataset)

            for param in param_keys:
                self.plot_parameter_boxplot(param, algo=None, filter_sets=filter_sets, key_to_name=key_to_name, expected_value=param_expected_values[param] if param_expected_values else None, search_space=param_search_space)
